// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tstxbtqtvpnnxbvopcuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzdHhidHF0dnBubnhidm9wY3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTY5OTksImV4cCI6MjA2NDczMjk5OX0.ERYBt4I2lrVZOvGi7cdRiM7uMe_zhkd6Lt2ZkpSDbvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);